#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\App;

require __DIR__ . '/vendor/autoload.php';

const BASE_PATH = __DIR__;

$config = require __DIR__ . '/config.php';

$config['inHours'] = isset($argv[2]) && $argv[2] === '-h';

$date = !isset($argv[1]) || $argv[1] === 'now' ? null : $argv[1];
$app = new App($config, $date);

echo $app->day() . PHP_EOL;
echo $app->month() . PHP_EOL;
